import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Flex, Text, Heading, VStack, HStack, List, Image, IconButton, Grid, GridItem, Input, Button } from '@chakra-ui/react';
import { useNavigate } from 'react-router-dom';
export default function HomePage() {
    return _jsxs(Flex, { bg: "greyscale.surface.subtle", w: "full", flexDir: "column", alignItems: "center", px: "5xl", children: [_jsx(IntroductionSection, {}), _jsx(ProjectsSection, {}), _jsx(AboutSection, {}), _jsx(ContactSection, {})] });
}
function IntroductionSection() {
    return _jsxs(Flex, { flexDir: "row", justify: "space-between", w: "full", py: "5xl", children: [_jsxs(VStack, { w: "794px", gap: "2xl", children: [_jsx(Heading, { textStyle: "h1.bold", color: "greyscale.text.title", children: "Hi, I\u2019m Sean, a software engineer." }), _jsx(Text, { textStyle: "h5.base", color: "greyscale.text.body", children: "I build websites that communicate your values and deliver customer satisfaction." })] }), _jsx(ContactDetails, {})] });
}
function ContactDetails() {
    return _jsxs(VStack, { alignItems: "start", children: [_jsx(Heading, { textStyle: "h6.bold", color: "greyscale.text.title", children: "Contact Details" }), _jsxs(List.Root, { mt: "l", listStyle: "none", gap: "md", children: [_jsx(List.Item, { children: _jsx(Text, { textStyle: "bodyLarge.base", color: "greyscale.text.body", children: "seanlenghaoen@gmail.com" }) }), _jsx(List.Item, { children: _jsx(Text, { textStyle: "bodyLarge.base", color: "greyscale.text.body", children: "+65 82209031" }) })] }), _jsx(Heading, { textStyle: "h6.bold", color: "greyscale.text.title", mt: "2xl", children: "Other Links" }), _jsxs(List.Root, { mt: "l", listStyle: "none", flexDir: "row", gap: "md", children: [_jsx(List.Item, { children: _jsx(IconButton, { rounded: "full", w: "3rem", h: "3rem", bg: "none", border: "1px solid", borderColor: "greyscale.border.default", as: "a", onClick: function () { window.location.href = "https://www.linkedin.com/in/sean-leng-ab44322b1/"; }, children: _jsx(Image, { src: "/assets/icons/linkedin.svg" }) }) }), _jsx(List.Item, { children: _jsx(IconButton, { rounded: "full", w: "3rem", h: "3rem", bg: "none", border: "1px solid", borderColor: "greyscale.border.default", onClick: function () { window.location.href = "https://github.com/Seanlhe"; }, children: _jsx(Image, { src: "/assets/icons/githubIcon.svg" }) }) })] })] });
}
function ProjectsSection() {
    var navigate = useNavigate();
    return _jsxs(VStack, { w: "full", alignItems: "start", py: "5xl", gap: "2xl", children: [_jsx(Heading, { textStyle: "h1.bold", color: "greyscale.text.title", children: "Projects" }), _jsxs(Grid, { templateColumns: "repeat(12, 1fr)", gap: "2xl", w: "full", children: [_jsxs(GridItem, { display: "flex", flexDir: "column", colSpan: 7, cursor: "pointer", onClick: function () { navigate("/homehelpy"); }, children: [_jsx(Image, { h: "25rem", w: "full", rounded: "l", mb: "l", src: "/assets/images/homehelpy_mockup.svg" }), _jsx(Text, { textStyle: "h6.bold", color: "greyscale.text.title", mb: "md", children: "HOMEHELPY" }), _jsx(Text, { textStyle: "bodyLarge.base", color: "greyscale.text.body", children: "UIUX design, web development" })] }), _jsxs(GridItem, { display: "flex", flexDir: "column", colSpan: 5, w: "full", cursor: "pointer", onClick: function () { navigate("/centsible"); }, children: [_jsx(Image, { bg: "black", h: "25rem", w: "full", rounded: "l", mb: "l", src: "/assets/images/centsible_mockup.svg" }), _jsx(Text, { textStyle: "h6.bold", color: "greyscale.text.title", mb: "md", children: "CENTSIBLE" }), _jsx(Text, { textStyle: "bodyLarge.base", color: "greyscale.text.body", children: "UIUX design, mobile app development" })] }), _jsxs(GridItem, { display: "flex", flexDir: "column", colSpan: 5, w: "full", cursor: "pointer", onClick: function () { navigate("/optistaff"); }, children: [_jsx(Image, { bg: "black", h: "25rem", w: "full", rounded: "l", mb: "l", src: "/assets/images/optistaff_mockup.svg" }), _jsx(Text, { textStyle: "h6.bold", color: "greyscale.text.title", mb: "md", children: "OPTISTAFF" }), _jsx(Text, { textStyle: "bodyLarge.base", color: "greyscale.text.body", children: "UIUX design, web development" })] }), _jsxs(GridItem, { display: "flex", flexDir: "column", colSpan: 7, children: [_jsx(Image, { bg: "black", h: "25rem", w: "full", rounded: "l", mb: "l" }), _jsx(Text, { textStyle: "h6.bold", color: "greyscale.text.title", mb: "md", children: "EVENT HORIZON (COMING SOON)" }), _jsx(Text, { textStyle: "bodyLarge.base", color: "greyscale.text.body", children: "UIUX design, web development" })] })] })] });
}
function AboutSection() {
    return _jsxs(Flex, { w: "100vw", py: "5xl", px: "5xl", bg: "greyscale.surface.default", flexDir: "column", gap: "2xl", children: [_jsx(Heading, { textStyle: "h1.bold", color: "greyscale.text.title", children: "About Me" }), _jsxs(HStack, { w: "full", justifyContent: "space-between", children: [_jsx(Image, { w: "39.5rem", h: "38rem", rounded: "l", bg: "greyscale.black", src: "/assets/images/profile_pic.svg" }), _jsxs(VStack, { w: "31rem", alignItems: "start", gap: "l", children: [_jsx(Text, { textStyle: "h4.bold", color: "greyscale.text.subtitle", children: "Who Am I?" }), _jsx(Text, { textStyle: "h5.base", color: "greyscale.text.body", children: "I\u2019m a UI/UX designer and software engineer in Singapore who loves collaborating with different brands. Each project pushes me to experiment with new design styles and create work that truly reflects a brand\u2019s personality. When I\u2019m not designing or coding, you\u2019ll probably find me reading about marketing or design, dancing street styles like locking and hip hop, or getting a workout in." })] })] })] });
}
function ContactSection() {
    return _jsxs(Flex, { w: "100vw", py: "5xl", px: "5xl", bg: "greyscale.surface.darker", flexDir: "row", alignItems: "flex-end", justifyContent: "space-between", gap: "2xl", children: [_jsxs(VStack, { w: "full", maxW: "35rem", gap: "l", alignItems: "start", children: [_jsx(Heading, { textStyle: "h1.bold", color: "greyscale.text.title", children: "Contact Me" }), _jsx(Text, { textStyle: "bodyLarge.base", color: "greyscale.text.body", children: "Have an opportunity and want to connect? Leave me a message." }), _jsxs(Grid, { templateColumns: "repeat(2, 1fr)", gap: "2xl", my: "xl", w: "full", children: [_jsx(GridItem, { children: _jsx(Input, { px: "0rem", placeholder: "FIRST NAME *", textStyle: "bodyRegular.base", color: "greyscale.text.body", border: "none", borderBottom: "1px solid", borderColor: "greyscale.border.default", rounded: "0rem", _placeholder: {
                                        color: "greyscale.text.body",
                                        opacity: 1,
                                    } }) }), _jsx(GridItem, { children: _jsx(Input, { px: "0rem", placeholder: "LAST NAME *", textStyle: "bodyRegular.base", color: "greyscale.text.body", border: "none", borderBottom: "1px solid", borderColor: "greyscale.border.default", rounded: "0rem", _placeholder: {
                                        color: "greyscale.text.body",
                                        opacity: 1,
                                    } }) }), _jsx(GridItem, { colSpan: 2, children: _jsx(Input, { px: "0rem", placeholder: "EMAIL *", textStyle: "bodyRegular.base", color: "greyscale.text.body", border: "none", borderBottom: "1px solid", borderColor: "greyscale.border.default", rounded: "0rem", _placeholder: {
                                        color: "greyscale.text.body",
                                        opacity: 1,
                                    } }) }), _jsx(GridItem, { colSpan: 2, children: _jsx(Input, { px: "0rem", placeholder: "ENQUIRY *", textStyle: "bodyRegular.base", color: "greyscale.text.body", border: "none", borderBottom: "1px solid", borderColor: "greyscale.border.default", rounded: "0rem", _placeholder: {
                                        color: "greyscale.text.body",
                                        opacity: 0.8,
                                    } }) })] }), _jsx(Button, { textStyle: "bodyRegular.base", bg: "greyscale.black", color: "greyscale.text.negative", rounded: "md", p: "l", children: "Send Message" })] }), _jsx(ContactDetails, {})] });
}
